# Generated by Django 3.2.3 on 2022-08-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
