# Generated by Django 3.0.4 on 2020-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200409_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailactivation',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_sent',
            field=models.BooleanField(default=True),
        ),
    ]
