# Generated by Django 3.0.4 on 2020-04-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200410_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_sent',
        ),
    ]
