# Generated by Django 3.2.3 on 2022-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200410_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
